Of course an exception is being thrown (you would be getting a - note also the edit regarding the url

